### ISSUE TITLE
The number of gaps will decrease after  running nextpolish2

### ISSUE THREAD

**Issue by zhoudreames** [Nextomics/NextPolish2#23]
My raw genome contains 45 gaps, the number of  gaps decrease to 41 after run the code "nextPolish2 -r -t 100 HiFi.bam ref.fa Illumina.k21.yak  Illumina.k31.yak >ref.polising_1.fa", while then umber of  gaps decrease to 35 when I add the parameter -r .
I don't know if this is a normal phenomenon, as I noticed that the usage method did not mention the function of filling gaps for  nextpolish2

**Comment by zhoudreames** [comment]
@kaichop @moold @WonderOmics @dongyawu   i am so sorry to disturb you, would you help me ? thanks

**Comment by moold** [comment]
Please don't @ people, because this is a free Q&A, especially people who are not related to this repository. If I am free, I will answer the question as soon as possible. If I don't have time, please just wait, I will reply later. To reiterate, this is a free Q&A.


`nextPolish2` does not contain gap filling steps, but if some gaps can be spaned by hifi reads, these gaps may be closed in some extreme cases. You can map hifi reads to the polished genome and use IGV to check the reliability of these gap filling regions.
